services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - my-network

#   python-app:
#     build:
#       context: .
#     container_name: python-app
#     depends_on:
#       - minio
#     networks:
#       - my-network
#     volumes:
#       - .:/app
#     tty: true

networks:
  my-network:

volumes:
  minio-data:
