version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - my-network

  python-app:
    build:
      context: .
    container_name: python-app
    networks:
      - my-network
    depends_on:
      - minio
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && python /app/init_minio.py && /bin/bash"

networks:
  my-network:

volumes:
  minio-data:
